language: scala
# Use container-based infrastructure
sudo: false
branches:
  only:
    - master
    - release
    - /^\d\.\d+$/
jdk:
  - oraclejdk8
scala:
  - 2.12.6
script:
  - sbt test
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.sbt
# Cleanup the cached directories to avoid unnecessary cache updates
before_cache:
  - find $HOME/.sbt        -name "*.lock"               -print -delete
